// Generated by scripts/generate-media-manifest.mjs
export const generatedPhotos = [
  {
    "id": "photo-1",
    "src": "/images/asmosphere%20(2).jpg",
    "category": "atmosphere"
  },
  {
    "id": "photo-2",
    "src": "/images/asmosphere%20(3).jpg",
    "category": "atmosphere"
  },
  {
    "id": "photo-3",
    "src": "/images/asmosphere%20(4).jpg",
    "category": "atmosphere"
  },
  {
    "id": "photo-4",
    "src": "/images/asmosphere%20(5).jpg",
    "category": "atmosphere"
  },
  {
    "id": "photo-5",
    "src": "/images/asmosphere%20(6).jpg",
    "category": "atmosphere"
  },
  {
    "id": "photo-6",
    "src": "/images/asmosphere%20(7).jpg",
    "category": "atmosphere"
  },
  {
    "id": "photo-7",
    "src": "/images/asmosphere%20(8).jpg",
    "category": "atmosphere"
  },
  {
    "id": "photo-8",
    "src": "/images/asmosphere.jpg",
    "category": "atmosphere"
  },
  {
    "id": "photo-9",
    "src": "/images/cake%20(2).jpg",
    "category": "cake"
  },
  {
    "id": "photo-10",
    "src": "/images/cake%20(3).jpg",
    "category": "cake"
  },
  {
    "id": "photo-11",
    "src": "/images/cake%20(4).jpg",
    "category": "cake"
  },
  {
    "id": "photo-12",
    "src": "/images/cake.jpg",
    "category": "cake"
  }
] as const
export const generatedTracks = [
  {
    "id": "track-1",
    "src": "/audio/song1.mp3",
    "title": "song 1",
    "artist": "Grandfa Farm Cafe"
  }
] as const
